-- Migration: Create academic_ranking table and link with public.professor
-- Generated on 2026-09-23

-- 1. Create academic_ranking table
CREATE TABLE IF NOT EXISTS public.academic_ranking (
    academic_ranking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    units_required NUMERIC NOT NULL DEFAULT 0,
    program TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Add foreign key column to professor table
ALTER TABLE public.professor
ADD COLUMN IF NOT EXISTS academic_ranking_id BIGINT REFERENCES public.academic_ranking(academic_ranking_id) ON DELETE SET NULL;

-- 3. Create indexes for efficient program filtering and joins
CREATE INDEX IF NOT EXISTS idx_academic_ranking_program ON public.academic_ranking(program);
CREATE INDEX IF NOT EXISTS idx_professor_academic_ranking_id ON public.professor(academic_ranking_id);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.academic_ranking ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies
DROP POLICY IF EXISTS "Allow authenticated read academic_ranking" ON public.academic_ranking;
CREATE POLICY "Allow authenticated read academic_ranking" ON public.academic_ranking
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow service role all academic_ranking" ON public.academic_ranking;
CREATE POLICY "Allow service role all academic_ranking" ON public.academic_ranking
    FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated insert academic_ranking" ON public.academic_ranking;
CREATE POLICY "Allow authenticated insert academic_ranking" ON public.academic_ranking
    FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated update academic_ranking" ON public.academic_ranking;
CREATE POLICY "Allow authenticated update academic_ranking" ON public.academic_ranking
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated delete academic_ranking" ON public.academic_ranking;
CREATE POLICY "Allow authenticated delete academic_ranking" ON public.academic_ranking
    FOR DELETE TO authenticated USING (true);

COMMENT ON TABLE public.academic_ranking IS 'Academic ranking designations with required teaching unit loads per program';
COMMENT ON COLUMN public.academic_ranking.name IS 'Name of the academic rank (e.g. Instructor I, Assistant Professor 1)';
COMMENT ON COLUMN public.academic_ranking.units_required IS 'Required teaching load in credit units';
COMMENT ON COLUMN public.academic_ranking.program IS 'Program code associated with this academic ranking';
COMMENT ON COLUMN public.professor.academic_ranking_id IS 'Foreign key referencing academic_ranking(academic_ranking_id)';
